import java.util.Random;
import java.util.Scanner;

class Project {
    public static void main(String[] args) {
        // number guessing game

        // step 1 : my java code should generate a random number
        Random random = new Random();
        int machineNumber = random.nextInt(1, 100);
      //  System.out.println("Number generated by machine: " + machineNumber);

        // step 2 : the user should enter a number
        Scanner input = new Scanner(System.in);
        System.out.print("Enter a number between 1 and 100: ");
        int userNumber = input.nextInt();
        System.out.println(userNumber);

        int count = 1;
        while (true) {

            // step 3 : check wheather thr number generated by java code is same as the
            // number entered by the user
            if (machineNumber == userNumber) {
                System.out.println("Congratulation!!!... You guessed the number in " + count + " chances");
                break;
            }
            // step 4 : if user number is greater than the machine number
            // msg - enter a smaller number
            else if (userNumber > machineNumber) {
                System.out.println("Enter a smaller Number than : " + userNumber);
                userNumber = input.nextInt();
            }

            // step 5 : if user number is smaller than the machine number
            // msg - enter a large number
            else if (userNumber < machineNumber) {
                System.out.println("Enter a larger Number than : " + userNumber);
                userNumber = input.nextInt();
            }
            count++;
        }

    }
}
